name: PUSH TOTAL - TestFlight

on:
  workflow_dispatch: {}

jobs:
  build_ios:
    name: Build iOS production
    type: build
    params:
      platform: ios
      profile: production

  testflight:
    name: Submit to TestFlight
    needs: [build_ios]
    type: testflight
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: production
