name: Update Production

on:
  push:
    branches: ['main']
    paths:
      - 'App.tsx'
      - 'index.js'
      - 'src/**'

jobs:
  update_production:
    name: Send iOS OTA update
    type: update
    environment: production
    params:
      platform: ios
      channel: production
