import React,{useState}from'react';
import{Linking,SafeAreaView,ScrollView,Text,TextInput,View}from'react-native';
import{AppState,FORM_VIDEO_URL,initialState,levelForReps,recommendedTestFromPushups}from'./core';
import{styles}from'./styles';import{Button,FormStep}from'./ui';
export function Onboarding({onDone}:{onDone:(next:AppState)=>void}){const[step,setStep]=useState<'intro'|'experience'|'form'|'pushup'|'experienced'|'recommend'>('intro');const[pushups,setPushups]=useState('');const[baemilgi,setBaemilgi]=useState('');const[recommendation,setRecommendation]=useState(10);
if(step==='intro')return <SafeAreaView style={styles.onboarding}><View style={styles.grow}><Text style={styles.kicker}>200 QUESTS · 1 YEAR</Text><Text style={styles.title}>배밀기{`\n`}2000</Text><Text style={styles.copy}>1년 뒤, 몇 개까지 갈 수 있을까?</Text></View><Button label="시작하기" onPress={()=>setStep('experience')}/></SafeAreaView>;
if(step==='experience')return <SafeAreaView style={styles.onboarding}><View style={styles.grow}><Text style={styles.kicker}>START</Text><Text style={styles.question}>배밀기를{`\n`}해본 적 있어?</Text><Text style={styles.copy}>처음이라면 자세부터. 해봤다면 지금 기록에서 시작해.</Text><View style={{gap:10,marginTop:30}}><Button label="처음이야" onPress={()=>setStep('form')}/><Button label="해봤어" secondary onPress={()=>setStep('experienced')}/></View></View></SafeAreaView>;
if(step==='form')return <SafeAreaView style={styles.onboarding}><ScrollView contentContainerStyle={{paddingBottom:24}}><Text style={styles.kicker}>OFFICIAL FORM</Text><Text style={styles.question}>이 앱에서{`\n`}1회로 세는 자세</Text><View style={{marginTop:20}}><FormStep n="1" title="엉덩이를 높여 시작" body="손을 고정하고 역 V자에 가깝게 시작."/><FormStep n="2" title="가슴을 앞으로" body="팔꿈치를 굽히며 가슴을 손 사이로 낮게 통과."/><FormStep n="3" title="팔을 펴고 가슴을 든다" body="앞으로 나간 뒤 팔을 펴며 상체를 들어 올림."/><FormStep n="4" title="팔을 편 채 뒤로" body="팔꿈치를 다시 굽히지 않고 엉덩이를 뒤·위로 보내 복귀."/></View><Text style={styles.note}>들어온 길을 팔꿈치를 다시 굽혀 되돌아가는 Dive Bomber 방식은 이 앱의 기준이 아니야.</Text><Button label="실제 자세 영상 보기" secondary onPress={()=>Linking.openURL(FORM_VIDEO_URL)}/><View style={{height:10}}/><Button label="이해했어" onPress={()=>setStep('pushup')}/></ScrollView></SafeAreaView>;
if(step==='pushup')return <SafeAreaView style={styles.onboarding}><View style={styles.grow}><Text style={styles.kicker}>STARTING POINT</Text><Text style={styles.question}>푸쉬업은 최대{`\n`}몇 개 가능해?</Text><Text style={styles.copy}>배밀기로 직접 환산하지 않아. 첫 배밀기 테스트 난이도 추천에만 사용해.</Text><TextInput value={pushups} onChangeText={setPushups} keyboardType="number-pad" placeholder="0" placeholderTextColor="#5F5B54" style={styles.bigInput}/></View><Button label="추천 보기" onPress={()=>{setRecommendation(recommendedTestFromPushups(Math.max(0,Number(pushups)||0)));setStep('recommend')}}/></SafeAreaView>;
if(step==='experienced')return <SafeAreaView style={styles.onboarding}><View style={styles.grow}><Text style={styles.kicker}>YOUR RECORD</Text><Text style={styles.question}>배밀기 최고 기록은?</Text><Text style={styles.copy}>이미 해낸 기록은 인정해. 높은 레벨을 깨면 아래 레벨도 모두 클리어돼.</Text><TextInput value={baemilgi} onChangeText={setBaemilgi} keyboardType="number-pad" placeholder="0" placeholderTextColor="#5F5B54" style={styles.bigInput}/></View><Button label="이 기록에서 시작" onPress={()=>{const reps=Math.max(1,Number(baemilgi)||1);const level=levelForReps(reps);onDone({...initialState,onboarded:true,firstBaemilgiMax:reps,clearedLevel:level,selectedLevel:Math.min(200,level+1)})}}/></SafeAreaView>;
return <SafeAreaView style={styles.onboarding}><View style={styles.grow}><Text style={styles.kicker}>FIRST TEST</Text><Text style={styles.question}>배밀기 {recommendation}개부터{`\n`}확인해보자.</Text><Text style={styles.copy}>푸쉬업 기록으로 계산한 배밀기 실력은 아니야. 첫 탐색 지점일 뿐이야.</Text></View><Button label={`${recommendation}개에서 시작`} onPress={()=>onDone({...initialState,onboarded:true,pushupMax:Math.max(0,Number(pushups)||0),selectedLevel:levelForReps(recommendation)})}/></SafeAreaView>}
