import { StyleSheet } from 'react-native';

export const C = {
  bg: '#F2EEE5',
  panel: '#F8F5EE',
  line: '#CFC7BA',
  text: '#211E1A',
  muted: '#746D63',
  faint: '#A59D91',
  accent: '#B94D32',
  accentSoft: '#E9D6CC',
  selected: '#27231F',
  danger: '#A6403D',
};

const labelFont = 'Avenir Next';
const numberFont = 'Georgia';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: C.bg },
  onboarding: { flex: 1, backgroundColor: C.bg, paddingHorizontal: 30, paddingBottom: 22 },

  introTop: { height: 64, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  introBrand: { color: C.text, fontSize: 14, fontWeight: '700', letterSpacing: -0.35 },
  introYear: { color: C.muted, fontSize: 12, fontFamily: labelFont, letterSpacing: 1.1 },
  introGrow: { flex: 1, justifyContent: 'center', alignItems: 'flex-start', paddingBottom: 12 },
  introEyebrow: { color: C.accent, fontSize: 11, fontFamily: labelFont, fontWeight: '700', letterSpacing: 1.7, marginBottom: 12 },
  introTitle: { color: C.text, fontSize: 88, lineHeight: 92, fontFamily: numberFont, fontWeight: '700', letterSpacing: -5 },
  introSub: { color: C.text, fontSize: 18, lineHeight: 26, fontWeight: '700', letterSpacing: -0.4, marginTop: 2 },
  introRule: { width: 42, height: 2, backgroundColor: C.accent, marginTop: 26, marginBottom: 22 },
  introCopy: { color: C.muted, fontSize: 15, lineHeight: 23, maxWidth: 330, marginBottom: 12 },
  introMeta: { color: C.faint, fontSize: 12, lineHeight: 18, maxWidth: 320, marginTop: 5 },

  setupTop: { height: 66, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderColor: C.line },
  setupBrand: { color: C.text, fontSize: 14, fontWeight: '700', letterSpacing: -0.3 },
  setupCount: { color: C.muted, fontSize: 12, fontFamily: labelFont, fontWeight: '600', letterSpacing: 0.8 },
  setupBody: { flex: 1, justifyContent: 'center', paddingBottom: 12 },
  setupScroll: { paddingTop: 42, paddingBottom: 24 },
  question: { color: C.text, fontSize: 36, lineHeight: 42, fontWeight: '800', letterSpacing: -1.7, maxWidth: 330 },
  copy: { color: C.muted, fontSize: 15, lineHeight: 23, marginTop: 15, maxWidth: 326 },

  choiceList: { marginTop: 38, borderTopWidth: StyleSheet.hairlineWidth, borderColor: C.line },
  choiceRow: { minHeight: 88, flexDirection: 'row', alignItems: 'center', gap: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: C.line },
  choiceTitle: { color: C.text, fontSize: 19, fontWeight: '700', letterSpacing: -0.5 },
  choiceBody: { color: C.muted, fontSize: 13, lineHeight: 19, marginTop: 4 },
  choiceArrow: { color: C.accent, fontSize: 22, fontWeight: '500' },

  formList: { marginTop: 30, borderTopWidth: StyleSheet.hairlineWidth, borderColor: C.line },
  formStep: { flexDirection: 'row', gap: 15, paddingVertical: 17, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: C.line },
  formN: { width: 24, color: C.accent, fontSize: 14, fontFamily: labelFont, fontWeight: '700' },
  formTitle: { color: C.text, fontSize: 15, fontWeight: '700' },
  formBody: { color: C.muted, fontSize: 13, lineHeight: 19, marginTop: 5 },
  note: { color: C.muted, borderLeftWidth: 2, borderColor: C.accent, paddingLeft: 12, fontSize: 12, lineHeight: 19, marginVertical: 22 },

  inputRow: { flexDirection: 'row', alignItems: 'baseline', borderBottomWidth: 1, borderColor: C.text, marginTop: 34 },
  bigInput: { flex: 1, color: C.text, fontSize: 76, lineHeight: 84, fontFamily: numberFont, fontWeight: '700', letterSpacing: -3, paddingVertical: 6 },
  inputUnit: { color: C.muted, fontSize: 18, fontWeight: '700', paddingBottom: 15 },
  inputHint: { color: C.faint, fontSize: 12, lineHeight: 18, marginTop: 10 },
  recommendLabel: { color: C.accent, fontSize: 12, fontWeight: '700', marginBottom: 2 },
  recommendInput: { flex: 1, color: C.text, fontSize: 92, lineHeight: 100, fontFamily: numberFont, fontWeight: '700', letterSpacing: -4, paddingVertical: 4 },
  recommendUnit: { color: C.text, fontSize: 20, fontWeight: '700', paddingBottom: 18 },
  recommendCopy: { color: C.muted, fontSize: 13, lineHeight: 20, marginTop: 10 },
  recommendRule: { height: StyleSheet.hairlineWidth, backgroundColor: C.line, marginVertical: 24 },

  kicker: { color: C.accent, fontSize: 10, fontFamily: labelFont, fontWeight: '700', letterSpacing: 1.5, marginBottom: 10 },
  title: { color: C.text, fontSize: 52, lineHeight: 55, fontWeight: '800', letterSpacing: -2.6 },

  button: { minHeight: 54, borderRadius: 8, backgroundColor: C.text, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 },
  buttonSecondary: { backgroundColor: 'transparent', borderWidth: 1, borderColor: C.line },
  buttonDanger: { backgroundColor: 'transparent', borderWidth: 1, borderColor: '#CDA8A4' },
  buttonText: { color: '#F8F5EE', fontSize: 15, fontWeight: '700', letterSpacing: -0.2 },
  buttonSecondaryText: { color: C.text },

  header: { height: 60, paddingHorizontal: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderColor: C.line },
  brand: { color: C.text, fontSize: 17, fontWeight: '700', letterSpacing: -0.6 },
  circle: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  circleText: { color: C.muted, fontSize: 19, fontWeight: '700' },

  page: { paddingHorizontal: 24, paddingTop: 28, paddingBottom: 106 },
  heroLevel: { color: C.text, fontSize: 48, lineHeight: 54, fontWeight: '800', letterSpacing: -2.2, marginTop: 4 },
  heroNumber: { color: C.text, fontSize: 82, lineHeight: 88, fontFamily: numberFont, fontWeight: '700', letterSpacing: -4, marginTop: 2 },
  heroUnit: { color: C.muted, fontSize: 14, fontWeight: '700', marginTop: -4 },
  progressTrack: { height: 4, backgroundColor: '#DCD5CA', marginTop: 24, overflow: 'hidden' },
  progressFill: { height: 4, backgroundColor: C.accent },
  metaRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 9 },
  mutedSmall: { color: C.muted, fontSize: 11, fontWeight: '600' },

  card: { borderTopWidth: 1, borderBottomWidth: 1, borderColor: C.line, paddingVertical: 24, marginTop: 34 },
  cardLevel: { color: C.muted, fontSize: 13, fontWeight: '700', marginBottom: 2 },
  cardNumber: { color: C.text, fontSize: 78, lineHeight: 84, fontFamily: numberFont, fontWeight: '700', letterSpacing: -4 },
  cardUnit: { color: C.muted, fontSize: 13, fontWeight: '600', marginTop: -2, marginBottom: 22 },

  linkRow: { minHeight: 64, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderColor: C.line },
  linkText: { color: C.text, fontSize: 14, fontWeight: '700' },
  linkArrow: { color: C.accent, fontSize: 21 },
  section: { marginTop: 30, paddingTop: 2 },
  sectionTitle: { color: C.text, fontSize: 15, fontWeight: '700' },
  sectionBody: { color: C.muted, fontSize: 13, lineHeight: 20, marginTop: 7 },

  pageTitle: { color: C.text, fontSize: 38, lineHeight: 43, fontWeight: '800', letterSpacing: -1.8 },
  pageCopy: { color: C.muted, fontSize: 14, lineHeight: 21, marginTop: 10, marginBottom: 24 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  cell: { width: '23.3%', aspectRatio: 1, borderWidth: 1, borderColor: C.line, backgroundColor: 'transparent', borderRadius: 5, padding: 9, justifyContent: 'space-between' },
  cellDone: { backgroundColor: C.accent, borderColor: C.accent },
  cellSelected: { backgroundColor: C.selected, borderColor: C.selected },
  cellLandmark: { borderWidth: 2, borderColor: '#8E7668' },
  cellLevel: { color: C.text, fontSize: 14, fontFamily: labelFont, fontWeight: '700' },
  cellReps: { color: C.muted, fontSize: 10, fontFamily: labelFont, fontWeight: '600' },
  cellTextInverse: { color: '#F9F6EF' },

  stats: { flexDirection: 'row', marginTop: 8, marginBottom: 32, borderTopWidth: StyleSheet.hairlineWidth, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: C.line },
  stat: { flex: 1, minHeight: 88, justifyContent: 'center', paddingVertical: 14 },
  statLabel: { color: C.muted, fontSize: 10, fontFamily: labelFont, fontWeight: '700', letterSpacing: 0.7 },
  statValue: { color: C.text, fontSize: 29, fontFamily: numberFont, fontWeight: '700', marginTop: 5 },
  historyRow: { minHeight: 74, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderColor: C.line, paddingVertical: 9 },
  historyMain: { color: C.text, fontSize: 14, fontWeight: '700' },
  historySub: { color: C.muted, fontSize: 11, marginTop: 5 },
  historyTarget: { color: C.text, fontSize: 18, fontFamily: numberFont, fontWeight: '700', textAlign: 'right' },
  historyEdit: { color: C.accent, fontSize: 11, fontWeight: '700', marginTop: 4, textAlign: 'right' },

  nav: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 72, backgroundColor: '#F2EEE5F4', borderTopWidth: StyleSheet.hairlineWidth, borderColor: C.line, flexDirection: 'row', paddingBottom: 7 },
  navButton: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  navText: { color: C.faint, fontSize: 12, fontWeight: '600' },
  navTextActive: { color: C.text, fontWeight: '800' },

  workout: { flex: 1, backgroundColor: C.bg, paddingHorizontal: 24, paddingBottom: 22 },
  workoutTop: { minHeight: 62, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderColor: C.line },
  workoutTitle: { color: C.muted, fontSize: 12, fontWeight: '700' },
  workoutGrow: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  workoutTarget: { color: C.text, fontSize: 118, lineHeight: 124, fontFamily: numberFont, fontWeight: '700', letterSpacing: -7 },
  workoutUnit: { color: C.muted, fontSize: 14, fontWeight: '700' },
  timer: { color: C.accent, fontSize: 22, fontFamily: labelFont, fontWeight: '700', marginTop: 26, fontVariant: ['tabular-nums'] },
  workoutHint: { color: C.muted, fontSize: 12, lineHeight: 19, textAlign: 'center', maxWidth: 300, marginTop: 20 },
  failureQuestion: { color: C.text, fontSize: 40, lineHeight: 45, fontWeight: '800', letterSpacing: -1.8, textAlign: 'center' },

  overlay: { flex: 1, backgroundColor: '#00000055', justifyContent: 'flex-end' },
  centerOverlay: { flex: 1, backgroundColor: '#00000055', justifyContent: 'center', padding: 22 },
  sheet: { backgroundColor: C.panel, borderTopLeftRadius: 14, borderTopRightRadius: 14, padding: 22, maxHeight: '90%' },
  sheetTitle: { color: C.text, fontSize: 27, lineHeight: 31, fontWeight: '800', letterSpacing: -1.2 },
  sheetCopy: { color: C.muted, fontSize: 14, lineHeight: 21, marginTop: 10, marginBottom: 14 },
  restoreInput: { minHeight: 150, color: C.text, backgroundColor: C.bg, borderWidth: 1, borderColor: C.line, borderRadius: 7, padding: 12, fontSize: 12, lineHeight: 18, textAlignVertical: 'top', marginVertical: 12 },
  messageCard: { backgroundColor: C.panel, borderRadius: 10, padding: 22 },
  messageText: { color: C.text, fontSize: 23, lineHeight: 30, fontWeight: '800', marginBottom: 20 },
});
