import { StyleSheet } from 'react-native';

export const C = {
  bg: '#F3EFE6',
  panel: '#FFFDF8',
  line: '#D8D0C3',
  text: '#1B1814',
  muted: '#6F685E',
  accent: '#C85537',
  accentSoft: '#F1D8CF',
  selected: '#1B1814',
  danger: '#B33C3C',
};

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: C.bg },
  onboarding: { flex: 1, backgroundColor: C.bg, paddingHorizontal: 36, paddingBottom: 24 },
  grow: { flex: 1, justifyContent: 'center' },
  introGrow: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  introTitle: { color: C.text, fontSize: 56, lineHeight: 58, fontWeight: '900', letterSpacing: -3, textAlign: 'center' },
  introCopy: { color: C.muted, fontSize: 16, lineHeight: 25, marginTop: 22, textAlign: 'center', maxWidth: 330 },
  introNote: { color: '#725649', backgroundColor: C.accentSoft, borderRadius: 12, paddingHorizontal: 15, paddingVertical: 12, fontSize: 12, lineHeight: 18, marginTop: 20, textAlign: 'center', maxWidth: 330 },
  choiceGrow: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 8 },
  choiceKicker: { color: C.accent, fontSize: 11, fontWeight: '900', letterSpacing: 1.5, marginBottom: 14, textAlign: 'center' },
  choiceQuestion: { color: C.text, fontSize: 40, lineHeight: 44, fontWeight: '900', letterSpacing: -2, textAlign: 'center', maxWidth: 280 },
  choiceCopy: { color: C.muted, fontSize: 16, lineHeight: 24, marginTop: 18, textAlign: 'center', maxWidth: 285 },
  choiceActions: { width: '100%', gap: 10, marginTop: 34 },
  kicker: { color: C.accent, fontSize: 11, fontWeight: '900', letterSpacing: 1.5, marginBottom: 14 },
  title: { color: C.text, fontSize: 58, lineHeight: 59, fontWeight: '900', letterSpacing: -3 },
  question: { color: C.text, fontSize: 41, lineHeight: 44, fontWeight: '900', letterSpacing: -2, maxWidth: 305 },
  copy: { color: C.muted, fontSize: 16, lineHeight: 24, marginTop: 18, maxWidth: 305 },
  bigInput: { color: C.text, fontSize: 88, fontWeight: '900', letterSpacing: -5, borderBottomWidth: 2, borderColor: C.text, paddingVertical: 14, marginTop: 30 },
  button: { minHeight: 56, borderRadius: 14, backgroundColor: C.accent, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 },
  buttonSecondary: { backgroundColor: C.panel, borderWidth: 1, borderColor: C.line },
  buttonDanger: { backgroundColor: 'transparent', borderWidth: 1, borderColor: '#D8A7A7' },
  buttonText: { color: '#FFF9F3', fontSize: 16, fontWeight: '900' },
  buttonSecondaryText: { color: C.text },
  formStep: { flexDirection: 'row', gap: 14, paddingVertical: 16, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: C.line },
  formN: { width: 26, color: C.accent, fontSize: 18, fontWeight: '900' },
  formTitle: { color: C.text, fontSize: 16, fontWeight: '800' },
  formBody: { color: C.muted, fontSize: 13, lineHeight: 19, marginTop: 5 },
  note: { color: '#5F574E', backgroundColor: C.panel, borderWidth: 1, borderColor: C.line, borderRadius: 12, padding: 15, fontSize: 13, lineHeight: 20, marginVertical: 16 },
  header: { height: 62, paddingHorizontal: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderColor: C.line },
  brand: { color: C.text, fontSize: 19, fontWeight: '900', letterSpacing: -0.8 },
  circle: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, borderColor: C.line, backgroundColor: C.panel, alignItems: 'center', justifyContent: 'center' },
  circleText: { color: C.text, fontSize: 20, fontWeight: '800' },
  page: { paddingHorizontal: 24, paddingTop: 22, paddingBottom: 112 },
  heroLevel: { color: C.text, fontSize: 44, fontWeight: '900', letterSpacing: -2.2, marginTop: 10 },
  progressTrack: { height: 7, borderRadius: 99, backgroundColor: '#DED7CC', marginTop: 22, overflow: 'hidden' },
  progressFill: { height: 7, borderRadius: 99, backgroundColor: C.accent },
  metaRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 10 },
  mutedSmall: { color: C.muted, fontSize: 11, fontWeight: '700' },
  card: { backgroundColor: C.panel, borderWidth: 1, borderColor: C.line, borderRadius: 18, padding: 22, marginTop: 28, shadowColor: '#000', shadowOpacity: 0.04, shadowRadius: 12, shadowOffset: { width: 0, height: 4 } },
  cardLevel: { color: C.text, fontSize: 24, fontWeight: '900', letterSpacing: -1 },
  cardNumber: { color: C.text, fontSize: 82, lineHeight: 86, fontWeight: '900', letterSpacing: -5, marginTop: 10 },
  cardUnit: { color: C.muted, fontSize: 14, fontWeight: '700', marginBottom: 22 },
  linkRow: { minHeight: 62, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderColor: C.line },
  linkText: { color: C.text, fontSize: 15, fontWeight: '800' },
  linkArrow: { color: C.accent, fontSize: 22 },
  section: { marginTop: 30, borderTopWidth: StyleSheet.hairlineWidth, borderColor: C.line, paddingTop: 18 },
  sectionTitle: { color: C.text, fontSize: 16, fontWeight: '900' },
  sectionBody: { color: C.muted, fontSize: 13, lineHeight: 20, marginTop: 7 },
  pageTitle: { color: C.text, fontSize: 41, lineHeight: 44, fontWeight: '900', letterSpacing: -2.1 },
  pageCopy: { color: C.muted, fontSize: 14, lineHeight: 21, marginTop: 10, marginBottom: 22 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  cell: { width: '23.1%', aspectRatio: 1, borderWidth: 1, borderColor: C.line, backgroundColor: C.panel, borderRadius: 12, padding: 10, justifyContent: 'space-between' },
  cellDone: { backgroundColor: C.accent, borderColor: C.accent },
  cellSelected: { backgroundColor: C.selected, borderColor: C.selected },
  cellLandmark: { borderWidth: 2, borderColor: '#9F5D46' },
  cellLevel: { color: C.text, fontSize: 16, fontWeight: '900' },
  cellReps: { color: C.muted, fontSize: 10, fontWeight: '700' },
  cellTextInverse: { color: '#FFF9F3' },
  stats: { flexDirection: 'row', gap: 8, marginTop: 8, marginBottom: 28 },
  stat: { flex: 1, backgroundColor: C.panel, borderWidth: 1, borderColor: C.line, borderRadius: 12, padding: 13 },
  statLabel: { color: C.muted, fontSize: 10, fontWeight: '700' },
  statValue: { color: C.text, fontSize: 24, fontWeight: '900', marginTop: 7 },
  historyRow: { minHeight: 76, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderColor: C.line, paddingVertical: 8 },
  historyMain: { color: C.text, fontSize: 14, fontWeight: '800' },
  historySub: { color: C.muted, fontSize: 11, marginTop: 5 },
  historyTarget: { color: C.text, fontSize: 18, fontWeight: '900' },
  historyEdit: { color: C.accent, fontSize: 12, fontWeight: '900', marginTop: 5, textAlign: 'right' },
  nav: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 74, backgroundColor: '#F3EFE6F5', borderTopWidth: StyleSheet.hairlineWidth, borderColor: C.line, flexDirection: 'row', paddingBottom: 8 },
  navButton: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  navText: { color: '#8D857A', fontSize: 12, fontWeight: '800' },
  navTextActive: { color: C.text },
  workout: { flex: 1, backgroundColor: C.bg, paddingHorizontal: 24, paddingBottom: 24 },
  workoutTop: { minHeight: 64, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  workoutTitle: { color: C.text, fontSize: 14, fontWeight: '900' },
  workoutGrow: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  workoutTarget: { color: C.text, fontSize: 120, lineHeight: 124, fontWeight: '900', letterSpacing: -8 },
  workoutUnit: { color: C.muted, fontSize: 16, fontWeight: '700' },
  timer: { color: C.accent, fontSize: 24, fontWeight: '900', marginTop: 28, fontVariant: ['tabular-nums'] },
  workoutHint: { color: C.muted, fontSize: 13, lineHeight: 20, textAlign: 'center', maxWidth: 310, marginTop: 22 },
  failureQuestion: { color: C.text, fontSize: 44, lineHeight: 47, fontWeight: '900', letterSpacing: -2, textAlign: 'center' },
  overlay: { flex: 1, backgroundColor: '#00000066', justifyContent: 'flex-end' },
  centerOverlay: { flex: 1, backgroundColor: '#00000066', justifyContent: 'center', padding: 22 },
  sheet: { backgroundColor: C.panel, borderTopLeftRadius: 20, borderTopRightRadius: 20, borderWidth: 1, borderColor: C.line, padding: 22, maxHeight: '90%' },
  sheetTitle: { color: C.text, fontSize: 30, lineHeight: 33, fontWeight: '900', letterSpacing: -1.5 },
  sheetCopy: { color: C.muted, fontSize: 14, lineHeight: 21, marginTop: 10, marginBottom: 14 },
  restoreInput: { minHeight: 150, color: C.text, backgroundColor: C.bg, borderWidth: 1, borderColor: C.line, borderRadius: 12, padding: 12, fontSize: 12, lineHeight: 18, textAlignVertical: 'top', marginVertical: 12 },
  messageCard: { backgroundColor: C.panel, borderWidth: 1, borderColor: C.line, borderRadius: 16, padding: 22 },
  messageText: { color: C.text, fontSize: 25, lineHeight: 32, fontWeight: '900', marginBottom: 20 },
});
